### ISSUE TITLE
nil dereference

### ISSUE THREAD

**Issue by pcj** [tcncloud/protoc-gen-persist#70]
Experimenting with this, got:

https://github.com/tcncloud/protoc-gen-persist/blob/154b37973d3dd54121e2375b2a88bdc9c8c50f8d/generator/method.go#L386

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5e2bb3]

goroutine 1 [running]:
github.com/tcncloud/protoc-gen-persist/generator.(*Method).GetTypeDescArrayForStruct(0xc420067530, 0x0, 0x1c, 0xc4201657c0, 0x1)
	external/com_github_tcn_protoc_gen_persist/generator/method.go:386 +0xc63
github.com/tcncloud/protoc-gen-persist/generator.(*SqlStringer).MapRequestToParams(0xc42000e0c0, 0xc420165c20, 0xc420018dd0)
	external/com_github_tcn_protoc_gen_persist/generator/backends.go:215 +0x258
github.com/tcncloud/protoc-gen-persist/generator.(*FileStruct).Generate(0xc4200739a0, 0x14, 0xc420165e48, 0x1, 0x1, 0xd)
	external/com_github_tcn_protoc_gen_persist/generator/file.go:415 +0x45e
github.com/tcncloud/protoc-gen-persist/generator.(*Generator).GetResponse(0xc42000c660, 0x0, 0x0, 0x82c000)
	external/com_github_tcn_protoc_gen_persist/generator/generator.go:66 +0x136
```

Have not added any options to the proto file yet, but that if statement looks suspicious.

**Comment by pcj** [comment]
Thanks!

**Comment by namtzigla** [comment]
Your welcome! We would like to hear back from you after you test it.
